python main.py \
  --data_dir /sailhome/yuhuiz/develop/data/MedicalImages/msd/processed/Task10_Colon/   \
  --split_json dataset_5slices.json \
  --img_size 512 512 5 \
  --clip_range -28 158 \
  --mean_std 70.43 31.84 \
  --in_channels 1 \
  --out_channels 2 \
  --max_steps 25000 \
  --train_batch_size 4 \
  --eval_batch_size 4
